apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default-spot-br
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["t3.large","m5.large","c5.large"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
  providerRef:
    name: bottlerocket-spot
  ttlSecondsAfterEmpty: 60
  consolidation:
    enabled: true
