name: Terraform CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init (backend disabled for CI)
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate

      - name: Speculative plan (no backend)
        run: terraform plan -lock=false -input=false -refresh=false -out=tfplan || true
